language: c

env:
  global:
    - RENV="./pkg-build.sh"
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"

  # R versions r-builder should test on
    - RVERSION=devel


before_install:
  - echo RENV=$RENV
  - curl -OL https://raw.githubusercontent.com/HenrikBengtsson/r-builder/master/pkg-build.sh;
  - chmod 755 $RENV
  - $RENV bootstrap

install:
  - $RENV install_bioc BiocGenerics 

script:

after_success:

after_failure:
  - $RENV dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  except:
   - /-expt$/
